### ISSUE TITLE
1.17.1 issue

### ISSUE THREAD

**Issue by Ramraids** [Darkere/moredragoneggs#1]
Hi,

Not really sure if you are maintaining this or not but it seems to cause a server crash on character load in.

I thought it was just my server machine was not fast enough which may well be the problem but I ran it on a faster machine to see if it made any difference and it didn't.

The server will start up fine and run fine but when my character loads in it will take between 20 seconds to 1 minute before it crashes sometimes much quicker.

Thanks if you bother fixing it and no worries if you don't.

cya

**Comment by Darkere** [comment]
I haven't ported this to 1.17...
